### ISSUE TITLE
Firebase auth signInWithCredential

### ISSUE THREAD

**Issue by modawoud** [EvanBacon/expo-native-firebase#10]
Hello,

I am using react-native-fbsdk to sign in users with facebook and firebase

I am using this function

```
try {
        const currentUser = await firebase
          .auth()
          .signInWithCredential(credential);
        } catch (e) {
        console.log(e);
      }
```

it works fine on both apple and android,

But if the user is disabled in firebase, it works only on IOS and throws an error

the problem is on android that the currentUser promise never returns anything, not an error nor nothing and it takes forever without returning when the user is disabled in firebase

it was working fine using rnFirebase, but when I switched to expo-native-firebase, it doesn't work when the user is disabled,

I am not sure what is causing this.

Thank you

**Comment by EvanBacon** [comment]
Should be resolved with the new expo-firebase rc.5 stuff!
