### ISSUE TITLE
I did all the steps, but it having warning : firebaseOptions missing or invalid 'apiKey' property

### ISSUE THREAD

**Issue by shubhamdeol** [EvanBacon/expo-native-firebase#12]
One more issue is this, I only need `expo-firebase-analytics`, But this never works, I had to import all the packages, performance, database, auth, functions... all. If we skip any, android app crashes saying error message like: can't find module `expo-firebase-auth`, even If don't use this. 

I tried using rn firebase as well, but it makes things more complicated, Their official doc says 
> "Due to some breaking changes in v12+ of the Android Firebase libraries, you'll need to upgrade your Gradle version to at least v4.4"

whereas expo eject guide does not recommend to upgrade.

In one of the post on medium you clearly mentioned this:
> "By having separate modules we can enable developers to create much slimmer apps. If there is a library you don’t want, or don’t need, just don’t include it"

But, I guess this does not work that way

Please help
@EvanBacon

**Comment by modawoud** [comment]
You can comment out the libraries you are not using inside node_modules/expo-firebase-app/src/utils/getModuleInstance.js
and it should work fine, But I am not sure if this is the perfect solution to this

**Comment by EvanBacon** [comment]
It appears as though you have 1 issue in the title, and a completely different issue in the description. Please take the time to open 2 separate issues.

> But, I guess this does not work that way

It does, exactly as I said in the article. I just tested it again: https://github.com/EvanBacon/expo-native-firebase/tree/%40evanbacon/analytics-example
