### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type NSException (lldb)

### ISSUE THREAD

**Issue by pramodxyle** [EvanBacon/expo-native-firebase#15]
I see this on iOS and can't get the app to launch. The app crashes with this at the splash screen. Android ver works well. How should I go about this ?

**Comment by Lugdum** [comment]
Same here. @pramodxyle did you find a fix for it?

**Comment by benfontan** [comment]
Figured it out myself. When calling `firebase.initializeApp`, I was not setting the plist converted to JSON as explained but the normal parameters from firebase Web SDK.

**Comment by pramodxyle** [comment]
> Figured it out myself. When calling `firebase.initializeApp`, I was not setting the plist converted to JSON as explained but the normal parameters from firebase Web SDK.

Yep, this is exactly what I did. Was just going to update this thread.

**Comment by pramodxyle** [comment]
Closing this issue.
