### ISSUE TITLE
On mac, run-exp.sh finished with non-zero exit value 127

### ISSUE THREAD

**Issue by crazedVic** [EvanBacon/expo-native-firebase#8]
org.gradle.process.internal.ExecException: Process 'command './node_modules/expokit/detach-scripts/run-exp.sh'' finished with non-zero exit value 127

contents of file:
#!/bin/bash
```

value=$(cat ~/.expo/PATH)
PATH="$PATH:$value" exp "$@"
# For testing
# PATH="$PATH:$value" ../../dev/exp/bin/exp.js "$@"
```

running these manually:
**MacBook-Pro:Egghunt user$ cat ~/.expo/PATH**
/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/sbin:/Users/user/.fastlane/bin:/Users/user/.composer/vendor/bin:/usr/local/mysql/bin:~/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/user/Library/Android/sdk/emulator:/Users/user/Library/Android/sdk/tools:/Users/user/Library/Android/sdk/tools/bin:/Users/user/Library/Android/sdk/platform

**MacBMacBook-Pro:Egghunt user$ PATH="$PATH:$value" exp "$@"**
-bash: exp: command not found

Should be expo not exp?

Or do i need to npm install -g exp

Doing either  - installing exp or using expo, let Android Studio build successfully..

though doing exp whoami says:
We've built a brand new CLI for Expo!
Expo CLI is a drop in replacement for exp.
Install: npm install -g expo-cli
Use: expo --help

So i guess either is fine?

**Comment by EvanBacon** [comment]
This is because I changed the name of the app in the `app.json` after detaching :/ just changed it back and now it starts
