### ISSUE TITLE
notification callbacks doesn't get called

### ISSUE THREAD

**Issue by BlazJurisic** [EvanBacon/expo-native-firebase#9]
onNotificationOpened()
onNotificationDisplayed()
onNotification()

after tapping on notification, both in background and when app is killed, none of above callbacks doesn't get called. Because of that, I cant override opening handler.

Expo CLI 2.2.4 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.1.0 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.2
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
    npmGlobalPackages:
      expo-cli: 2.2.4

**Comment by EvanBacon** [comment]
Fixed in `expo-firebase rc-5`! 😁
